import { Toaster } from "@/components/ui/sonner";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";

const space = Space_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`${space.className}`}>
          {children}
          <Toaster
            position="bottom-right"
            expand={true}
            richColors
            theme="dark"
            closeButton
            style={{ marginBottom: "20px" }}
          />
        </body>
      </html>
    </ClerkProvider>
  );
}
