import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import QueryProviderWrapper from "@/components/wrappers/query-provider";
import { CompilerProvider } from "@/context/compiler-context";
import { ThemeProvider } from "@/components/wrappers/theme-provider";
import { ProjectProvider } from "@/context/project-context";
import { SessionProvider } from "next-auth/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <QueryProviderWrapper>
          <ProjectProvider>
            <CompilerProvider>
              {children}
              <Toaster
                position="bottom-right"
                expand={true}
                richColors
                theme="dark"
                closeButton
                style={{ marginBottom: "20px" }}
              />
            </CompilerProvider>
          </ProjectProvider>
        </QueryProviderWrapper>
      </body>
    </html>
  );
}
